version: "3.8"
services:
  sharply_app:
    container_name: sharply_app
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    expose:
      - 9000
    volumes:
      - .:/usr/src/app
      - ./public:/usr/src/app/public
    depends_on:
      - sharply_db
    networks:
      - app_network

  sharply_nginx:
    container_name: sharply_nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - ./public:/usr/src/app/public
    ports:
      - 8000:80
    depends_on:
      - sharply_app
    environment:
      NGINX_FPM_HOST: sharply_app
      NGINX_ROOT: /usr/src/app/public
    networks:
      - app_network

  sharply_db:
    container_name: sharply_db
    image: postgres:10.1
    restart: always
    volumes:
      - ./storage/db-data:/var/lib/mysql
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: sharply
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - app_network
networks:
  app_network:
    driver: bridge
